export const sentences = [
    "The cat sat on the mat.",
    "I love to read books.",
    "She runs very fast.",
    "The sun is shining brightly.",
    "It is a sunny day outside.",
    "I like to eat apples.",
    "Dogs are loyal animals.",
    "I have a blue car.",
    "My favorite color is blue.",
    "The ball bounced high.",
    "Birds are singing in the trees.",
    "I enjoy watching movies on weekends.",
    "The flowers are blooming in the garden.",
    "My sister loves playing the piano.",
    "We had a picnic by the lake.",
    "Apples are delicious and healthy.",
    "He is my best friend.",
    "I like to walk in the park.",
    "The sun rises in the east.",
    "I need to buy groceries today.",
    "I went to the zoo yesterday.",
    "My mom makes the best soup.",
    "He is reading a book now.",
    "They play soccer after school.",
    "The house is very big.",
    "I like to play chess.",
    "We went to the beach last weekend.",
    "I see many birds outside.",
    "My dog loves to play fetch.",
    "The moon is bright tonight.",
    "The sky is blue today.",
    "I am learning to play the guitar.",
    "He is very good at math.",
    "The park is full of people.",
    "I see a rainbow in the sky.",
    "My brother is very tall.",
    "She wears a red dress.",
    "We have dinner at 7 PM.",
    "I like to go swimming in the pool.",
    "I am writing a letter to my friend.",
    "The quick brown fox jumps over the lazy dog.",
    "A journey of a thousand miles begins with a single step.",
    "Practice makes perfect in everything we do.",
    "Life is what happens when you're busy making other plans.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "The early bird catches the worm every time.",
    "You can’t use up creativity. The more you use, the more you have.",
    "Dreams are the touchstones of our character.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The coffee was hot and freshly brewed.",
    "It’s important to stay active every day.",
    "I saw a rainbow after the rainstorm.",
    "The chocolate cake tastes so sweet.",
    "This book is filled with amazing adventures.",
    "Traveling opens your mind to new experiences.",
    "Hard work pays off in the long run.",
    "Nature is the best medicine for stress.",
    "Time flies when you’re having fun.",
    "Every day is a new beginning.",
    "I love learning new languages.",
    "Reading helps to improve your knowledge.",
    "Cooking is a wonderful skill to learn.",
    "I enjoy exploring new places.",
    "The internet has made life easier.",
    "The weather is perfect for a walk.",
    "It's important to eat a balanced diet.",
    "I enjoy painting in my free time.",
    "Playing sports keeps you healthy.",
    "I love the sound of the ocean.",
    "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.",
    "It is never too late to be what you might have been.",
    "The only way to do great work is to love what you do.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "In the end, we will remember not the words of our enemies, but the silence of our friends.",
    "Life isn't about finding yourself, it's about creating yourself.",
    "That which does not kill us makes us stronger.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "You must be the change you wish to see in the world.",
    "Life is really simple, but we insist on making it complicated.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The way to get started is to quit talking and begin doing.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "A person who never made a mistake never tried anything new.",
    "The best way to predict your future is to create it.",
    "You miss 100% of the shots you don't take.",
    "If you want to go fast, go alone. If you want to go far, go together.",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful.",
    "In the middle of difficulty lies opportunity.",
    "Our lives begin to end the day we become silent about things that matter.",
    "The power of imagination makes us infinite.",
    "It’s not the years in your life that count, it’s the life in your years.",
    "You don't have to be great to start, but you have to start to be great.",
    "Don't watch the clock; do what it does. Keep going.",
    "The only thing standing between you and your goal is the story you keep telling yourself.",
    "Believe you can and you're halfway there.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "To succeed in life, you need two things: ignorance and confidence.",
    "It always seems impossible until it's done.",
    "The road to success and the road to failure are almost exactly the same."
  ];
  